[2025-06-01T11:04:42.526+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: second_dag.save_data_task scheduled__2020-09-28T00:00:00+00:00 [queued]>
[2025-06-01T11:04:42.550+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: second_dag.save_data_task scheduled__2020-09-28T00:00:00+00:00 [queued]>
[2025-06-01T11:04:42.556+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 3
[2025-06-01T11:04:42.620+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): save_data_task> on 2020-09-28 00:00:00+00:00
[2025-06-01T11:04:42.634+0000] {standard_task_runner.py:57} INFO - Started process 16516 to run task
[2025-06-01T11:04:42.643+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'second_dag', 'save_data_task', 'scheduled__2020-09-28T00:00:00+00:00', '--job-id', '805', '--raw', '--subdir', 'DAGS_FOLDER/my_second_dag.py', '--cfg-path', '/tmp/tmp5_c60mbf']
[2025-06-01T11:04:42.648+0000] {standard_task_runner.py:85} INFO - Job 805: Subtask save_data_task
[2025-06-01T11:04:42.789+0000] {task_command.py:410} INFO - Running <TaskInstance: second_dag.save_data_task scheduled__2020-09-28T00:00:00+00:00 [running]> on host 27c4b93144a0
[2025-06-01T11:04:43.148+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='second_dag' AIRFLOW_CTX_TASK_ID='save_data_task' AIRFLOW_CTX_EXECUTION_DATE='2020-09-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2020-09-28T00:00:00+00:00'
[2025-06-01T11:04:43.161+0000] {my_second_dag.py:50} INFO - Fetching value USD: None
[2025-06-01T11:04:43.174+0000] {base.py:73} INFO - Using connection ID 'pg_database' for task execution.
[2025-06-01T11:04:43.188+0000] {my_second_dag.py:63} INFO - Check conn:                                              version
0  PostgreSQL 13.20 (Debian 13.20-1.pgdg120+1) on...
[2025-06-01T11:04:43.188+0000] {logging_mixin.py:150} INFO - Data saved successfully.
[2025-06-01T11:04:43.189+0000] {python.py:183} INFO - Done. Returned value was: None
[2025-06-01T11:04:43.199+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=second_dag, task_id=save_data_task, execution_date=20200928T000000, start_date=20250601T110442, end_date=20250601T110443
[2025-06-01T11:04:43.227+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2025-06-01T11:04:43.245+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
