[2025-06-01T16:35:07.912+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: second_dag.save_data_task scheduled__2024-05-16T00:00:00+00:00 [queued]>
[2025-06-01T16:35:07.924+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: second_dag.save_data_task scheduled__2024-05-16T00:00:00+00:00 [queued]>
[2025-06-01T16:35:07.924+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 3
[2025-06-01T16:35:08.142+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): save_data_task> on 2024-05-16 00:00:00+00:00
[2025-06-01T16:35:08.150+0000] {standard_task_runner.py:57} INFO - Started process 67663 to run task
[2025-06-01T16:35:08.164+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'second_dag', 'save_data_task', 'scheduled__2024-05-16T00:00:00+00:00', '--job-id', '3895', '--raw', '--subdir', 'DAGS_FOLDER/my_second_dag.py', '--cfg-path', '/tmp/tmp1njw6m3u']
[2025-06-01T16:35:08.167+0000] {standard_task_runner.py:85} INFO - Job 3895: Subtask save_data_task
[2025-06-01T16:35:08.245+0000] {task_command.py:410} INFO - Running <TaskInstance: second_dag.save_data_task scheduled__2024-05-16T00:00:00+00:00 [running]> on host 27c4b93144a0
[2025-06-01T16:35:08.520+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='second_dag' AIRFLOW_CTX_TASK_ID='save_data_task' AIRFLOW_CTX_EXECUTION_DATE='2024-05-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-16T00:00:00+00:00'
[2025-06-01T16:35:08.533+0000] {my_second_dag.py:51} INFO - Fetching value USD: 91.2573
[2025-06-01T16:35:08.547+0000] {base.py:73} INFO - Using connection ID 'pg_database' for task execution.
[2025-06-01T16:35:08.558+0000] {logging_mixin.py:150} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:313 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2025-06-01T16:35:08.560+0000] {my_second_dag.py:69} INFO - Data saved successfully.
[2025-06-01T16:35:08.561+0000] {python.py:183} INFO - Done. Returned value was: None
[2025-06-01T16:35:08.571+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=second_dag, task_id=save_data_task, execution_date=20240516T000000, start_date=20250601T163507, end_date=20250601T163508
[2025-06-01T16:35:08.658+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2025-06-01T16:35:08.679+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
