[2025-06-01T18:03:01.350+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: second_dag.save_data_task scheduled__2002-08-08T00:00:00+00:00 [queued]>
[2025-06-01T18:03:01.371+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: second_dag.save_data_task scheduled__2002-08-08T00:00:00+00:00 [queued]>
[2025-06-01T18:03:01.371+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 3
[2025-06-01T18:03:01.671+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): save_data_task> on 2002-08-08 00:00:00+00:00
[2025-06-01T18:03:01.683+0000] {standard_task_runner.py:57} INFO - Started process 27466 to run task
[2025-06-01T18:03:01.692+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'second_dag', 'save_data_task', 'scheduled__2002-08-08T00:00:00+00:00', '--job-id', '6560', '--raw', '--subdir', 'DAGS_FOLDER/my_second_dag.py', '--cfg-path', '/tmp/tmpb3f7i5ag']
[2025-06-01T18:03:01.696+0000] {standard_task_runner.py:85} INFO - Job 6560: Subtask save_data_task
[2025-06-01T18:03:01.749+0000] {task_command.py:410} INFO - Running <TaskInstance: second_dag.save_data_task scheduled__2002-08-08T00:00:00+00:00 [running]> on host 40869fde016f
[2025-06-01T18:03:01.847+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='second_dag' AIRFLOW_CTX_TASK_ID='save_data_task' AIRFLOW_CTX_EXECUTION_DATE='2002-08-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2002-08-08T00:00:00+00:00'
[2025-06-01T18:03:01.869+0000] {my_second_dag.py:51} INFO - Fetching value USD: 31.5542
[2025-06-01T18:03:01.887+0000] {base.py:73} INFO - Using connection ID 'pg_database' for task execution.
[2025-06-01T18:03:01.898+0000] {logging_mixin.py:150} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:313 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2025-06-01T18:03:01.900+0000] {my_second_dag.py:69} INFO - Data saved successfully.
[2025-06-01T18:03:01.900+0000] {python.py:183} INFO - Done. Returned value was: None
[2025-06-01T18:03:01.924+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=second_dag, task_id=save_data_task, execution_date=20020808T000000, start_date=20250601T180301, end_date=20250601T180301
[2025-06-01T18:03:01.992+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2025-06-01T18:03:02.027+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
