[2025-06-01T18:03:07.977+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: second_dag.save_data_task scheduled__2002-08-20T00:00:00+00:00 [queued]>
[2025-06-01T18:03:08.121+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: second_dag.save_data_task scheduled__2002-08-20T00:00:00+00:00 [queued]>
[2025-06-01T18:03:08.122+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 3
[2025-06-01T18:03:08.157+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): save_data_task> on 2002-08-20 00:00:00+00:00
[2025-06-01T18:03:08.167+0000] {standard_task_runner.py:57} INFO - Started process 27870 to run task
[2025-06-01T18:03:08.185+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'second_dag', 'save_data_task', 'scheduled__2002-08-20T00:00:00+00:00', '--job-id', '6588', '--raw', '--subdir', 'DAGS_FOLDER/my_second_dag.py', '--cfg-path', '/tmp/tmp_ykltxx2']
[2025-06-01T18:03:08.188+0000] {standard_task_runner.py:85} INFO - Job 6588: Subtask save_data_task
[2025-06-01T18:03:08.256+0000] {task_command.py:410} INFO - Running <TaskInstance: second_dag.save_data_task scheduled__2002-08-20T00:00:00+00:00 [running]> on host 40869fde016f
[2025-06-01T18:03:08.482+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='second_dag' AIRFLOW_CTX_TASK_ID='save_data_task' AIRFLOW_CTX_EXECUTION_DATE='2002-08-20T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2002-08-20T00:00:00+00:00'
[2025-06-01T18:03:08.504+0000] {my_second_dag.py:51} INFO - Fetching value USD: 31.555
[2025-06-01T18:03:08.515+0000] {base.py:73} INFO - Using connection ID 'pg_database' for task execution.
[2025-06-01T18:03:08.528+0000] {logging_mixin.py:150} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:313 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2025-06-01T18:03:08.530+0000] {my_second_dag.py:69} INFO - Data saved successfully.
[2025-06-01T18:03:08.531+0000] {python.py:183} INFO - Done. Returned value was: None
[2025-06-01T18:03:08.540+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=second_dag, task_id=save_data_task, execution_date=20020820T000000, start_date=20250601T180307, end_date=20250601T180308
[2025-06-01T18:03:08.594+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2025-06-01T18:03:08.619+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
