[2025-06-01T09:54:29.243+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: second_dag.feth_data_task scheduled__2000-01-07T00:00:00+00:00 [queued]>
[2025-06-01T09:54:29.256+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: second_dag.feth_data_task scheduled__2000-01-07T00:00:00+00:00 [queued]>
[2025-06-01T09:54:29.256+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 2
[2025-06-01T09:54:29.287+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): feth_data_task> on 2000-01-07 00:00:00+00:00
[2025-06-01T09:54:29.305+0000] {standard_task_runner.py:57} INFO - Started process 4438 to run task
[2025-06-01T09:54:29.314+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'second_dag', 'feth_data_task', 'scheduled__2000-01-07T00:00:00+00:00', '--job-id', '157', '--raw', '--subdir', 'DAGS_FOLDER/my_second_dag.py', '--cfg-path', '/tmp/tmp99qlojpd']
[2025-06-01T09:54:29.323+0000] {standard_task_runner.py:85} INFO - Job 157: Subtask feth_data_task
[2025-06-01T09:54:29.424+0000] {task_command.py:410} INFO - Running <TaskInstance: second_dag.feth_data_task scheduled__2000-01-07T00:00:00+00:00 [running]> on host 27c4b93144a0
[2025-06-01T09:54:29.835+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='second_dag' AIRFLOW_CTX_TASK_ID='feth_data_task' AIRFLOW_CTX_EXECUTION_DATE='2000-01-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2000-01-07T00:00:00+00:00'
[2025-06-01T09:54:29.846+0000] {logging_mixin.py:150} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:313 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2025-06-01T09:54:29.847+0000] {my_second_dag.py:21} INFO - Fetching data for date: 2000-01-07
[2025-06-01T09:54:29.918+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/my_second_dag.py", line 32, in fetch_data_from_api
    data = pd.read_xml(io.StringIO(xml_data), parser='etree')\
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/xml.py", line 938, in read_xml
    storage_options=storage_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/xml.py", line 728, in _parse
    data_dicts = p.parse_data()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/xml.py", line 215, in parse_data
    self._validate_path()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/xml.py", line 323, in _validate_path
    raise ValueError(msg)
ValueError: xpath does not return any nodes. If document uses namespaces denoted with xmlns, be sure to define namespaces and use them in xpath.
[2025-06-01T09:54:29.942+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=second_dag, task_id=feth_data_task, execution_date=20000107T000000, start_date=20250601T095429, end_date=20250601T095429
[2025-06-01T09:54:29.957+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 157 for task feth_data_task (xpath does not return any nodes. If document uses namespaces denoted with xmlns, be sure to define namespaces and use them in xpath.; 4438)
[2025-06-01T09:54:29.988+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2025-06-01T09:54:30.031+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
