[2025-06-02T18:32:24.327+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: second_dag.save_data_task scheduled__2003-02-11T00:00:00+00:00 [queued]>
[2025-06-02T18:32:24.338+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: second_dag.save_data_task scheduled__2003-02-11T00:00:00+00:00 [queued]>
[2025-06-02T18:32:24.338+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 3
[2025-06-02T18:32:24.359+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): save_data_task> on 2003-02-11 00:00:00+00:00
[2025-06-02T18:32:24.368+0000] {standard_task_runner.py:57} INFO - Started process 3506 to run task
[2025-06-02T18:32:24.383+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'second_dag', 'save_data_task', 'scheduled__2003-02-11T00:00:00+00:00', '--job-id', '6935', '--raw', '--subdir', 'DAGS_FOLDER/my_second_dag.py', '--cfg-path', '/tmp/tmp_410w5uj']
[2025-06-02T18:32:24.385+0000] {standard_task_runner.py:85} INFO - Job 6935: Subtask save_data_task
[2025-06-02T18:32:24.485+0000] {task_command.py:410} INFO - Running <TaskInstance: second_dag.save_data_task scheduled__2003-02-11T00:00:00+00:00 [running]> on host 40869fde016f
[2025-06-02T18:32:24.741+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='second_dag' AIRFLOW_CTX_TASK_ID='save_data_task' AIRFLOW_CTX_EXECUTION_DATE='2003-02-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2003-02-11T00:00:00+00:00'
[2025-06-02T18:32:24.762+0000] {my_second_dag.py:52} INFO - Fetching value USD: 31.8214
[2025-06-02T18:32:24.784+0000] {base.py:73} INFO - Using connection ID 'pg_database' for task execution.
[2025-06-02T18:32:24.794+0000] {logging_mixin.py:150} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:313 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2025-06-02T18:32:24.796+0000] {my_second_dag.py:65} INFO - Saving exchange rate 31.82 for date 2003-02-11
[2025-06-02T18:32:24.798+0000] {python.py:183} INFO - Done. Returned value was: None
[2025-06-02T18:32:24.806+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=second_dag, task_id=save_data_task, execution_date=20030211T000000, start_date=20250602T183224, end_date=20250602T183224
[2025-06-02T18:32:24.842+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2025-06-02T18:32:24.859+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
