[2025-06-01T16:30:10.305+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: second_dag.save_data_task scheduled__2022-07-16T00:00:00+00:00 [queued]>
[2025-06-01T16:30:10.329+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: second_dag.save_data_task scheduled__2022-07-16T00:00:00+00:00 [queued]>
[2025-06-01T16:30:10.330+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 3
[2025-06-01T16:30:10.362+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): save_data_task> on 2022-07-16 00:00:00+00:00
[2025-06-01T16:30:10.380+0000] {standard_task_runner.py:57} INFO - Started process 48655 to run task
[2025-06-01T16:30:10.388+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'second_dag', 'save_data_task', 'scheduled__2022-07-16T00:00:00+00:00', '--job-id', '2554', '--raw', '--subdir', 'DAGS_FOLDER/my_second_dag.py', '--cfg-path', '/tmp/tmp3lst6yke']
[2025-06-01T16:30:10.390+0000] {standard_task_runner.py:85} INFO - Job 2554: Subtask save_data_task
[2025-06-01T16:30:10.457+0000] {task_command.py:410} INFO - Running <TaskInstance: second_dag.save_data_task scheduled__2022-07-16T00:00:00+00:00 [running]> on host 27c4b93144a0
[2025-06-01T16:30:10.755+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='second_dag' AIRFLOW_CTX_TASK_ID='save_data_task' AIRFLOW_CTX_EXECUTION_DATE='2022-07-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-07-16T00:00:00+00:00'
[2025-06-01T16:30:10.763+0000] {my_second_dag.py:51} INFO - Fetching value USD: 57.8323
[2025-06-01T16:30:10.770+0000] {base.py:73} INFO - Using connection ID 'pg_database' for task execution.
[2025-06-01T16:30:10.780+0000] {logging_mixin.py:150} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:313 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2025-06-01T16:30:10.782+0000] {my_second_dag.py:69} INFO - Data saved successfully.
[2025-06-01T16:30:10.782+0000] {python.py:183} INFO - Done. Returned value was: None
[2025-06-01T16:30:10.790+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=second_dag, task_id=save_data_task, execution_date=20220716T000000, start_date=20250601T163010, end_date=20250601T163010
[2025-06-01T16:30:10.843+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2025-06-01T16:30:10.859+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
